# Change these first
owner: rizzolessio
repo: upptime-eusa

# Add your sites here
sites:
  - name: European Startup Association
    url: https://eustartupassociation.com
    icon: https://eustartupassociation.com/wp-content/uploads/2020/04/eusa_favicon-32.png
  - name: AFGE
    url: https://afge.legal
    icon: https://afge.legal/wp-content/uploads/2021/01/afge_favicon-64-2.png
  - name: Sanicode
    url: https://sanicode.app
    icon: https://sanicode.app/wp-content/uploads/ipad-icon-sanicode-2x.png
  - name: TherAbility
    url: https://therability.toys/en
    icon: https://therability.toys/wp-content/uploads/cropped-TA_MONOGRAM_COLOR.png
  - name: BEF Biosystems
    url: https://bef.bio

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-eusa
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime EuSA marketing
  introTitle: "**EuSA Upptime** is a open-source uptime monitor and status page for the EUropean Startup Association marketing team."
  introMessage: This is a status page which uses **real-time** data updated every 5 minutes. Create your own from the [Upptime repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
