# Change these first
owner: rizzolessio
repo: upptime-eusa

# Add your sites here
sites:
  - name: European Startup Association
    url: https://eustartupassociation.com
    icon: https://i.imgur.com/WLknArv.png
  - name: AFGE
    url: https://afge.legal
    icon: https://i.imgur.com/CJasJ87.png
  - name: Sanicode
    url: https://sanicode.app
    icon: https://i.imgur.com/OxbOygL.png
  - name: TherAbility
    url: https://therability.toys/en
    icon: https://i.imgur.com/IPpghVo.png
  - name: BEF Biosystems
    url: https://bef.bio
    icon: https://i.imgur.com/UZ2dpCV.png
    

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-eusa
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime EuSA marketing
  introTitle: "**EuSA Upptime** is an open-source uptime monitor for the Eu Startup Association team."
  introMessage: This is a status page which uses **real-time** data updated every 5 minutes.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
